version: "3.9"
services:
  proxy:
    container_name: proxy
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - front
      - back
    depends_on:
      - frontend
      - api
  api:
    container_name: api
    build: ./Backend/
    ports:
      - "5000:5000"
    networks: 
      - back
  frontend:
    build: ./frontend/
    depends_on: 
      - api
    networks:
      - front

networks:
  front: 
    driver: bridge
  back:
    driver: bridge